version: 1.0.{build}
image:
- ubuntu1804

build_script:
- sh build.sh

artifacts:
- path: bin
  name: GrowtopiaServer

deploy:
- provider: GitHub
  description: GrowtopiaServer CI Build
  auth_token:
    secure: 5OeKL0BpXE39SdxcoJ6mZH7EcELGBCnKLHavhELhYtQxuVmt9ZnQu5GzsAOh1rM+
